name: deploy to Tencent Cloud(be)

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lowcode-svc/server
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: use node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_SECRET }}
          ARGS: -avz --delete --exclude='.env'
          SERVER_PORT: "22"
          FOLDER: ./lowcode-svc/server/*
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: /workspace/slidEverywhere/server

      # - name: Restart server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_SECRET }}
      #     script: |
      #       cd /workspace/slidEverywhere/server
      #       yarn pro
